PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
ZSH=/home/root/.oh-my-zsh
TERM=linux
ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd/mm/yyyy"
plugins=(
  zsh-syntax-highlighting git autojump command-not-found python pip github gnu-utils zsh-completion zsh-autosuggestions history-substring-search
)
source $ZSH/oh-my-zsh.sh
export EDITOR='nano'
export ARCHFLAGS="-arch x86_64"
export LANG="de_DE.UTF-8"

alias zshconfig="nano ~/.zshrc"
alias ohmyzsh="nano ~/.oh-my-zsh"

